...

diff --git a/src/bin/sql b/src/bin/sql
--- a/src/bin/sql
+++ b/src/bin/sql
@@ -1,44 +1,48 @@
 #!/bin/bash
 
+# api_version=1
 
-. $VNODECTRL_LIB/common
 
+sql_info() {
+    echo "Control MySQL on guest system"
+}
 
-if [ ! $# -eq 0 ]; then
-	bootstrap $2
-else
-	${1:-@}
-fi
+sql_exec() {
+    local \
+        guest_user=$(vnode_identity_get 'guest_user') \
+        guest_pass=$(vnode_identity_get 'guest_pass') \
+        guest_addr=$(vnode_identity_get 'guest_addr')
 
-case $1 in
-	cli)
-		ssh -q -oStrictHostKeyChecking=no -t $GUEST_USER@$GUEST_ADDR "mysql -uroot"
-		
-		exit $?
-	;;
-	dump)
-		ssh -q -oStrictHostKeyChecking=no $GUEST_USER@$GUEST_ADDR "sudo -k; echo $GUEST_PASS | sudo -S ~/guest/sql-dump.sh" | tail -n +1
-		
-		R=$?
-		if [ ! $R -eq 0 ]; then
-		    echo "Error: $R"
-		fi
-		
-		exit 0
-	;;
-	restore)
-		ssh -q -oStrictHostKeyChecking=no $GUEST_USER@$GUEST_ADDR "sudo -k; echo $GUEST_PASS | sudo -S ~/guest/sql-restore.sh" | tail -n +1
-		
-		R=$?
-        if [ ! $R -eq 0 ]; then
-            echo "Error: $R"
-        fi
-		
-		exit 0
-	;;
-	*)
-		echo "Usage: `basename $0` {cli|dump|restore}"
-		
-		exit 1
-	;;
-esac
+    case $1 in
+    	cli)
+    		ssh -q -oStrictHostKeyChecking=no -t $guest_user@$guest_addr "mysql -uroot"
+    		
+    		exit $?
+    	;;
+    	dump)
+    		ssh -q -oStrictHostKeyChecking=no $guest_user@$guest_addr "sudo -k; echo $guest_pass | sudo -S ~/guest/sql-dump.sh" | tail -n +1
+    		
+    		R=$?
+    		if [ ! $R -eq 0 ]; then
+    		    echo "Error: $R"
+    		fi
+    		
+    		exit 0
+    	;;
+    	restore)
+    		ssh -q -oStrictHostKeyChecking=no $guest_user@$guest_addr "sudo -k; echo $guest_pass | sudo -S ~/guest/sql-restore.sh" | tail -n +1
+    		
+    		R=$?
+            if [ ! $R -eq 0 ]; then
+                echo "Error: $R"
+            fi
+    		
+    		exit 0
+    	;;
+    	*)
+    		echo "Usage: `basename $0` {cli|dump|restore}"
+    		
+    		exit 1
+    	;;
+    esac
+}
